adding upload download option for chat client config
digiteinfotech/kairon pull request #594
Opened 2022-06-07 07:30 UTC by hiteshghuge

2022-06-08 11:08 UTC, udit-pandey requested changes
Tests:
1. Upload without chat client config
2. Upload with hat client config
3. upload only chat client config
4. validate chat client validation erros are being logged
5.  upload only chat client config should not trigger event
6. upload empty chat client file, empty dict chat client file
7. upload chat client config in append mode

2022-06-08 11:08 UTC, udit-pandey commented on tests/unit_test/utility_test.py
> +            training_data = processor.load_nlu("test_load_from_path_yml_training_files")
move out of with block

2022-06-08 11:19 UTC, udit-pandey commented on tests/unit_test/utility_test.py
> +            training_data = processor.load_nlu("test_load_from_path_yml_training_files")
rebase from digiteinfotech/master

2022-06-08 11:54 UTC, hiteshghuge commented on kairon/shared/data/processor.py
>          if not validation_failed and not error_summary.get('config'):
added

2022-06-08 11:55 UTC, hiteshghuge commented on template/use-cases/Covid-19/chat_client_config.yml
> +name: kairon
Not possible

2022-06-09 13:57 UTC, hiteshghuge commented on kairon/shared/data/processor.py
>          if not validation_failed and not error_summary.get('config'):
done

2022-06-09 13:58 UTC, hiteshghuge commented on tests/unit_test/data_processor/data_processor_test.py
> +                list(TrainingExamples.objects(intent="greet", bot="test_upload_and_save", user="rules_creator"))) == 2
done

2022-12-28 04:21 UTC, closed without merging